Use custom hsnw::ParallelFor instead of omp for adding points
biovault/HDILib pull request #26
Opened 2021-03-19 10:59 UTC by alxvth

Use a nmslib function from https://github.com/nmslib/nmslib/blob/v2.1.1/similarity_search/include/thread_pool.h#L62 to add points in parallel since the omp parallel for causes some problems.

This seems to fix #25

2021-03-19 11:57 UTC, JulianThijssen requested changes
Looks fine to me, but on linux it's failing. Likely because pthreads isnt in the compile instructions of cmake.

2021-03-19 14:49 UTC, alxvth commented
Yes, pthreads was missing. It builds on linux and mac now.

2021-03-19 15:56 UTC, jeggermont commented
I think it should also be changed in hierarchical_sne.inl

2021-03-29 14:19 UTC, JulianThijssen approved these changes

2021-03-31 13:08 UTC, merged